plugins {
    id 'com.android.application'
}

android {
    namespace 'com.givan.fakestorage'
    compileSdk 33

    defaultConfig {
        applicationId 'com.givan.fakestorage'
        minSdk 26
        targetSdk 33
        versionCode 1
        versionName '1.0'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

repositories {
    google()
    mavenCentral()
    maven { url 'https://api.xposed.info/' }
}

dependencies {
    compileOnly 'de.robv.android.xposed:api:82'
}
